; Script generated by AutoBuilder 0.9f Prototype

#region ---Head--
#include <Constants.au3>
#include <GUIConstantsEx.au3>
#include <Misc.au3>
#include <WindowsConstants.au3>

#include <EditConstants.au3>
#include <ButtonConstants.au3>

Global $hGUI, $unknown, $punto, $plusslashminus, $plus,$minus,$por,$slash,$percent,$parentesis,$C
create_form()
#endregion ---Head---

#region --- Form ---

func create_form()
global $aNums[]
$hGUI=GuiCreate("Calculadora", 384, 311, -1, -1)

$unknown = GuiCtrlCreateInput("", 40, 0, 230, 110,-1)
$punto = GuiCtrlCreateButton(".", 150, 260, 50, 50,-1)
$aNums[0] = GuiCtrlCreateLabel("0", 100, 260, 50, 50,-1)
$plusslashminus = GuiCtrlCreateButton("+/-", 50, 260, 50, 50,-1)
$aNums[1] = GuiCtrlCreateLabel("1", 50, 210, 50, 50,-1)
$aNums[2] = GuiCtrlCreateLabel("2", 100, 210, 50, 50,-1)
$aNums[3] = GuiCtrlCreateLabel("3", 150, 210, 50, 50,-1)
$aNums[4] = GuiCtrlCreateLabel("4", 50, 160, 50, 50,-1)
$aNums[5] = GuiCtrlCreateLabel("5", 100, 160, 50, 50,-1)
$aNums[6] = GuiCtrlCreateLabel("6", 150, 160, 50, 50,-1)
$aNums[7] = GuiCtrlCreateLabel("7", 50, 110, 50, 50,-1)
$aNums[8] = GuiCtrlCreateLabel("8", 100, 110, 50, 50,-1)
$aNums[9] = GuiCtrlCreateLabel("9", 150, 110, 50, 50,-1)
$plus = GuiCtrlCreateButton("+", 200, 240, 40, 70,-1)
$minus = GuiCtrlCreateButton("-", 200, 190, 40, 50,-1)
$por = GuiCtrlCreateButton("x", 200, 150, 40, 50,-1)
$slash = GuiCtrlCreateButton("/", 200, 110, 40, 50,-1)
$percent = GuiCtrlCreateButton("%", 10, 260, 40, 50,-1)
$parentesis = GuiCtrlCreateButton("()", 10, 210, 40, 50,-1)
$C = GuiCtrlCreateButton("C", 10, 160, 40, 50,-1)

GuiSetState(@sw_SHOW)
endfunc
#EndRegion --- Form ---

#region --- Loop ---
While 1
$idMsg = GuiGetMsg()
switch $idMsg
case $GUI_EVENT_CLOSE
ExitLoop
case $aNums[0] to $aNums[9]
For $I = 0 to 9
if $idMsg = $aNums[$I] then
beep(1000, 60)
$sText = ControlGetText($hGUI, "", "Edit1")
ControlSetText($hGUI, "", "Edit1", $sText &ControlGetText($hGUI, "", $aNums[$I]))
EndIf
sleep(20)
Next
EndSwitch
WEnd
#Endregion --- Loop ---

#Region --- Additional Functions ---
#Endregion --- Additional Functions ---

Exit

