#include <Constants.au3>
#include <GUIConstantsEx.au3>
#include <Misc.au3>
#include <WindowsConstants.au3>
#include <EditConstants.au3>
#include <StaticConstants.au3>
#include <ListBoxConstants.au3>
#include <ButtonConstants.au3>

#Region (=== GUI generated by GuiBuilderPlus 1.0.0-beta ===)
Global $hGUI = GUICreate("""", 400, 350, 290, 257)

Global $calculadora = GUICtrlCreateInput("", 170, 0, 220, 110)
GUICtrlSetColor(-1, 0x000000)
Global $CERO = GUICtrlCreateLabel("0", 140, 280, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $PUNTO = GUICtrlCreateLabel(".", 170, 280, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $IGUAL = GUICtrlCreateLabel("=", 220, 280, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $NUEVE = GUICtrlCreateLabel("9", 210, 160, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $OCHO = GUICtrlCreateLabel("8", 170, 160, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $CUATRO = GUICtrlCreateLabel("4", 130, 200, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $UNO = GUICtrlCreateLabel("1", 140, 240, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $CINCO = GUICtrlCreateLabel("5", 170, 200, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $SEIS = GUICtrlCreateLabel("6", 210, 200, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $SIETE = GUICtrlCreateLabel("7", 130, 160, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $TRES = GUICtrlCreateLabel("3", 220, 240, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $DOS = GUICtrlCreateLabel("2", 180, 240, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $PORCENTAJE = GUICtrlCreateLabel("%", 130, 130, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $MENOS = GUICtrlCreateLabel("-", 250, 240, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $POR = GUICtrlCreateLabel("X", 250, 200, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $DIVISOR = GUICtrlCreateLabel("/", 250, 160, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $MÁS = GUICtrlCreateLabel("+", 260, 280, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $ABRIRPARENTECIS = GUICtrlCreateLabel("(", 160, 130, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $CERRARPARENTECIS = GUICtrlCreateLabel(")", 200, 130, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $BORRAR = GUICtrlCreateLabel("C", 240, 130, 30, 30)
GUICtrlSetColor(-1, 0x000000)
Global $FORMULAS = GUICtrlCreateList("", 10, 110, 90, 149)
GUICtrlSetColor(-1, 0x000000)
Global $opciones = GUICtrlCreateLabel("opciones", 40, 260, 60, 70)
GUICtrlSetColor(-1, 0x000000)
Global $razon = GUICtrlCreateButton("razón", 280, 110, 40, 50)
GUICtrlSetColor(-1, 0x000000)
Global $idEtiquetaInput = GUICtrlCreateLabel("Escribir operación", 10, 10, 160, 90)
GUICtrlSetColor(-1, 0x000000)
Global $idEtiquetarLista = GUICtrlCreateLabel("Comandos disponibles:", 280, 170, 80, 30)
GUICtrlSetColor(-1, 0x000000)
Global $idAbout = GUICtrlCreateButton("acerca de", 280, 210, 80, 50)
GUICtrlSetColor(-1, 0x000000)
#EndRegion (=== GUI generated by GuiBuilderPlus 1.0.0-beta ===)

_main()

;------------------------------------------------------------------------------
; Title...........:	_main
; Description.....:	run the main program loop
;------------------------------------------------------------------------------
Func _main()
	GUISetState(@SW_SHOWNORMAL)

	While 1
		Switch GUIGetMsg()
			Case $GUI_EVENT_CLOSE
				ExitLoop

			Case Else
				;
		EndSwitch
	WEnd
EndFunc   ;==>_main

