#include <Constants.au3>
#include <GUIConstantsEx.au3>
#include <Misc.au3>
#include <WindowsConstants.au3>
#include <EditConstants.au3>
#include <StaticConstants.au3>
#include <ListBoxConstants.au3>
#include <ButtonConstants.au3>

#Region (=== GUI generated by GuiBuilderPlus 1.0.0-beta ===)
Global $hGUI = GUICreate("""", 392, 432, 290, 257)
GUISetBkColor(0x951722)

Global $calculadora = GUICtrlCreateInput("", 10, 30, 370, 60)
GUICtrlSetColor(-1, 0x000000)
Global $CERO = GUICtrlCreateLabel("0", 187, 281, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $PUNTO = GUICtrlCreateLabel(".", 227, 281, 30, 30, $SS_CENTER)
GUICtrlSetFont(-1, 15)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $IGUAL = GUICtrlCreateLabel("=", 267, 281, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $NUEVE = GUICtrlCreateLabel("9", 227, 161, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $OCHO = GUICtrlCreateLabel("8", 187, 161, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $CUATRO = GUICtrlCreateLabel("4", 147, 201, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $UNO = GUICtrlCreateLabel("1", 147, 241, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $CINCO = GUICtrlCreateLabel("5", 187, 201, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $SEIS = GUICtrlCreateLabel("6", 227, 201, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $SIETE = GUICtrlCreateLabel("7", 147, 161, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $TRES = GUICtrlCreateLabel("3", 227, 241, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $DOS = GUICtrlCreateLabel("2", 187, 241, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $PORCENTAJE = GUICtrlCreateLabel("%", 147, 281, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $MENOS = GUICtrlCreateLabel("-", 267, 201, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $POR = GUICtrlCreateLabel("x", -270, 300, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetColor(-1, 0x000000)
Global $DIVISOR = GUICtrlCreateLabel("/", 267, 121, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $MÁS = GUICtrlCreateLabel("+", 267, 241, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $ABRIRPARENTECIS = GUICtrlCreateLabel("(", 147, 121, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $CERRARPARENTECIS = GUICtrlCreateLabel(")", 187, 121, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $BORRAR = GUICtrlCreateLabel("C", 227, 121, 30, 30, BitOR($SS_CENTER, $SS_CENTERIMAGE))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $FORMULAS = GUICtrlCreateList("", 10, 140, 130, 249)
GUICtrlSetColor(-1, 0x000000)
Global $Comandos = GUICtrlCreateLabel("Comandos", 10, 120, 130, 20, BitOR($SS_CENTERIMAGE, $SS_CENTER))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $Razón = GUICtrlCreateButton("Razón", 307, 121, 70, 30)
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0x000000)
Global $idEtiquetaInput = GUICtrlCreateLabel("Escribir operación", 10, 10, 370, 20, BitOR($SS_CENTERIMAGE, $SS_CENTER))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
Global $idAbout = GUICtrlCreateButton("Acerca de...", 147, 321, 70, 50)
GUICtrlSetColor(-1, 0x000000)
Global $POR = GUICtrlCreateLabel("x", 267, 161, 30, 30, BitOR($SS_CENTERIMAGE, $SS_CENTER))
GUICtrlSetFont(-1, 10)
GUICtrlSetColor(-1, 0xFFFFFF)
GUICtrlSetBkColor(-1, 0x828282)
#EndRegion (=== GUI generated by GuiBuilderPlus 1.0.0-beta ===)

_main()

;------------------------------------------------------------------------------
; Title...........:	_main
; Description.....:	run the main program loop
;------------------------------------------------------------------------------
Func _main()
	GUISetState(@SW_SHOWNORMAL)

	While 1
		Switch GUIGetMsg()
			Case $GUI_EVENT_CLOSE
				ExitLoop

			Case Else
				;
		EndSwitch
	WEnd
EndFunc   ;==>_main

