; Script generated by AutoBuilder 0.9f Prototype

#region ---Head--
#include <Constants.au3>
#include <GUIConstantsEx.au3>
#include <Misc.au3>
#include <WindowsConstants.au3>

#include <EditConstants.au3>
#include <StaticConstants.au3>
#include <ListBoxConstants.au3>

Global $hGUI,$calculadora,$CERO,$PUNTO,$IGUAL,$NUEVE,$OCHO,$CUATRO,$UNO,$CINCO,$SEIS,$SIETE,$TRES,$DOS,$PORCENTAJE,$MENOS,$POR,$DIVISOR,$MÁS,$ABRIRPARENTECIS,$CERRARPARENTECIS,$BORRAR,$FORMULAS
create_form()
#endregion ---Head---

#region --- Form ---

func create_form()
$hGUI=GuiCreate("MyGUI", 384, 311, -1, -1, $WS_OVERLAPPED + $WS_CAPTION + $WS_SYSMENU + $WS_VISIBLE + $WS_CLIPSIBLINGS + $WS_MINIMIZEBOX)

$calculadora = GuiCtrlCreateInput("", 10, 0, 370, 110,-1)
$CERO = GuiCtrlCreateLabel("0", 140, 280, 30, 30,-1)
$PUNTO = GuiCtrlCreateLabel(".", 170, 280, 30, 30,bitor($SS_GRAYFRAME,$SS_WHITERECT,0,0))
GUICtrlSetBkColor(-1,0x000000)
$IGUAL = GuiCtrlCreateLabel("=", 220, 280, 30, 30,bitor($SS_WHITERECT,0,0))
$NUEVE = GuiCtrlCreateLabel("9", 210, 160, 30, 30,-1)
$OCHO = GuiCtrlCreateLabel("8", 170, 160, 30, 30,-1)
$CUATRO = GuiCtrlCreateLabel("4", 130, 200, 30, 30,-1)
$UNO = GuiCtrlCreateLabel("1", 140, 240, 30, 30,-1)
$CINCO = GuiCtrlCreateLabel("5", 170, 200, 30, 30,-1)
$SEIS = GuiCtrlCreateLabel("6", 210, 200, 30, 30,-1)
$SIETE = GuiCtrlCreateLabel("7", 130, 160, 30, 30,-1)
$TRES = GuiCtrlCreateLabel("3", 220, 240, 30, 30,-1)
$DOS = GuiCtrlCreateLabel("2", 180, 240, 30, 30,-1)
$PORCENTAJE = GuiCtrlCreateLabel("%", 130, 130, 30, 30,-1)
$MENOS = GuiCtrlCreateLabel("-", 250, 240, 30, 30,-1)
$POR = GuiCtrlCreateLabel("X", 250, 200, 30, 30,-1)
$DIVISOR = GuiCtrlCreateLabel("/", 250, 160, 30, 30,-1)
$MÁS = GuiCtrlCreateLabel("+", 260, 280, 30, 30,-1)
$ABRIRPARENTECIS = GuiCtrlCreateLabel("(", 160, 130, 30, 30,-1)
$CERRARPARENTECIS = GuiCtrlCreateLabel(")", 200, 130, 30, 30,-1)
$BORRAR = GuiCtrlCreateLabel("C", 240, 130, 30, 30,-1)
$FORMULAS = GuiCtrlCreateList("", 20, 120, 90, 149,-1)

GuiSetState()
endfunc
#EndRegion --- Form ---

#region --- Loop ---
While 1
	$msg = GuiGetMsg()
	Select
	Case $msg = $GUI_EVENT_CLOSE
		ExitLoop
	Case Else
		;;;
	EndSelect
WEnd
#Endregion --- Loop ---

#Region --- Additional Functions ---
#Endregion --- Additional Functions ---

Exit

