name: calculator

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: Windows-latest
##    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Cache tools
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            autoit-v3-setup.exe
            SciTE4AutoIt3.exe
            C:\Program Files (x86)\AutoIt3\SciTE\Au3Stripper
          key: v3
      - name: Download tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSfL https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe -o autoit-v3-setup.exe `
            -sSfL https://www.autoitscript.com/cgi-bin/getfile.pl?../autoit3/scite/download/SciTE4AutoIt3.exe -o SciTE4AutoIt3.exe `
            -sSfLO https://www.autoitscript.com/autoit3/scite/download/Au3Stripper.zip
          Expand-Archive Au3Stripper.zip "${env:ProgramFiles(x86)}\AutoIt3\SciTE\Au3Stripper"
      - name: Install tools
        run: |
          Start-Process autoit-v3-setup.exe -ArgumentList /S -NoNewWindow -Wait
          Start-Process SciTE4AutoIt3.exe -ArgumentList /S -NoNewWindow -Wait
      - name: Compiling
        run: |
          Start-Process "${env:ProgramFiles(x86)}\AutoIt3\AutoIt3.exe" "`"${env:ProgramFiles(x86)}\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3`" /NoStatus /prod /in calculator_GUI.au3" -NoNewWindow -Wait
      - name: Move executable
        run: |
          Move-Item D:/a/Universal-calculator/compiled/UniversalCalc.exe D:/a/Universal-calculator/Universal-calculator/
      - uses: actions/upload-artifact@v4
        with:
          name: calculator
          path: |
            Documentation\*\*.txt
            lng\*.lang
            lng\*.txt
            sounds\*.wav
            nvdaControllerClient32.dll
            UniversalCalc.exe
          if-no-files-found: error
      - name: Build portable and installable binaries
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          7z a universal_calculator.zip UniversalCalc.exe Documentation\ lng\ sounds\ *.dll
          Start-Process "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe" "setup.iss" -NoNewWindow -Wait
          Start-Process "${env:ProgramFiles(x86)}\AutoIt3\AutoIt3.exe" "`"${env:ProgramFiles(x86)}\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3`" /NoStatus /prod /in include\updater.au3" -NoNewWindow -Wait
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            universal_calculator.zip
            Output/universal_calculator_setup.exe
            include/updater.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
